apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hqnug0i29-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hqnug0i29-go 
  name: hqnug0i29-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hqnug0i29-go 
